name: snowflake-migration-git

on:
  push:
    branches:
      - main
    paths:
      - 'v1.1.1.sql'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: |
          echo "Installing schemachange"
          pip install schemachange

      - name: Run schemachange
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SF_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SF_DATABASE }}

        run: |
          echo "Running schemachange deployment"
          echo "Workspace: $GITHUB_WORKSPACE"

          schemachange deploy \
            --root-folder $GITHUB_WORKSPACE \
            --snowflake-account $SNOWFLAKE_ACCOUNT \
            --snowflake-user $SNOWFLAKE_USER \
            --snowflake-password $SNOWFLAKE_PASSWORD \
            --snowflake-role $SNOWFLAKE_ROLE \
            --snowflake-warehouse $SNOWFLAKE_WAREHOUSE \
            --snowflake-database $SNOWFLAKE_DATABASE \
            --change-history-table $SNOWFLAKE_DATABASE.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table
