name: snowflake-migration-git

on:
  push:
    branches:
      - main
    paths:
      - 'deploy'
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install schemachange
        run: |
          pip install schemachange

      - name: Create Snowflake connection file
        run: |
          mkdir -p ~/.snowflake
          cat <<EOF > ~/.snowflake/connections.toml
          [default]
          account = "${{ secrets.SF_ACCOUNT }}"
          user = "${{ secrets.SF_USERNAME }}"
          password = "${{ secrets.SF_PASSWORD }}"
          role = "${{ secrets.SF_ROLE }}"
          warehouse = "${{ secrets.SF_WAREHOUSE }}"
          database = "${{ secrets.SF_DATABASE }}"
          EOF

      - name: Run schemachange
        run: |
          echo "Running schemachange deployment"

          schemachange deploy \
            --connection-name default \
            --root-folder $GITHUB_WORKSPACE \
            --change-history-table ${{ secrets.SF_DATABASE }}.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table
