name: snowflake-migration-git

on: 
 push:
   branchs:
     -main
   paths:
     -'v1.1.1.sql'
 workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
       -name: Checkout repository
        uses: actions/checkout@v2

      -name: Use python 3.8.x
       uses: actions/setup-python@v2.2.1
       with:
         python-version: 3.8.x

      -name: Run schemachange
       env:
         SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
         SF_USERNAME: ${{ secrets.SF_USERNAME }}
         SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
         SF_ROLE: ${{ secrets.SF_ROLE }}
         SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
         SF_DATABASE: ${{ secrets.SF_DATABASE }}



      run:  |
         echo "GITHUB WORKSPACE: $GITHUB_WORKSPACE"
         python --version
         echo "Step 1: Installing schemachange"
         pip install schema change

         echo "Step 2 : Running schemachange"
         schemachange -f $GITHUB_WORKSPACE/v1.1.1.sql -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -C $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY  --create-change-history-table
