name: Snowflake SQL Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-sql:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.28-linux_x86_64.bash
          bash snowsql-1.2.28-linux_x86_64.bash -y
          export PATH=$HOME/bin:$PATH
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify SnowSQL
        run: |
          snowsql -v

      - name: Run SQL Scripts
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
          SF_SCHEMA: ${{ secrets.SF_SCHEMA }}

        run: |
          snowsql -a $SF_ACCOUNT \
                  -u $SF_USERNAME \
                  -p $SF_PASSWORD \
                  -r $SF_ROLE \
                  -w $SF_WAREHOUSE \
                  -d $SF_DATABASE \
                  -s $SF_SCHEMA \
                  -f sql/create_table.sql

          snowsql -a $SF_ACCOUNT \
                  -u $SF_USERNAME \
                  -p $SF_PASSWORD \
                  -r $SF_ROLE \
                  -w $SF_WAREHOUSE \
                  -d $SF_DATABASE \
                  -s $SF_SCHEMA \
                  -f sql/load_data.sql
